# Generated by Django 5.0.1 on 2024-02-13 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascent',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ascent',
            name='video',
            field=models.FileField(null=True, upload_to='ascents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
